version: "3.8"
services:
  server:
    container_name: gigabot_server
    build:
      context: ./services/server
      dockerfile: .dockerfile
      args:
        - NODE_ENV=production
    networks:
      - frontend
      - backend
    ports:
      - 8001:7000
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:7000/api/v1/status || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  core:
    container_name: gigabot_core
    build:
      context: ./services/core
      dockerfile: .dockerfile
      args:
        - NODE_ENV=production
    networks:
      - backend
    ports:
      - 8002:7001
    depends_on:
      server:
        condition: service_healthy
    restart: unless-stopped


networks:
  frontend:
    name: gigabot_frontend
  backend:
    name: gigabot_backend
